---
title: \Large Costs of primary healthcare visits and hospitalizations for scabies and bacterial skin infections in Fiji
author: " "

number-sections: true

crossref:
  title-delim: "."

format:
  pdf:
    papersize: a4
    fontsize: "12pt"
    link-citations: true
    linestretch: 1.5
    geometry:
    - top=25.4mm
    - left=25.4mm
    - right=25.4mm
    - bottom=25.4mm
    template-partials: 
      - title.tex
    header-includes: |
      \usepackage[labelsep=period, labelfont=bf, textfont=normal]{caption}
      \usepackage[noblocks]{authblk}
      \renewcommand*{\Authsep}{, }
      \renewcommand*{\Authand}{, }
      \renewcommand*{\Authands}{, }
      \renewcommand\Authfont{\large} 
      \renewcommand\Affilfont{\normalsize}
 
mainfont: "Helvetica Neue"
sansfont: "Helvetica Neue"
---

```{r setup}
#| output: false
#| echo: false

library(tidyverse)
library(gtsummary)
library(flextable)
library(officer)

knitr::opts_chunk$set(fig.width = 12, fig.height = 10, fig.align = "center", ft.tabcolsep = 4,
                      out.width = "100%", collapse = TRUE, fig.pos = "H", out.extra = "")

knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")})
# 
# set_flextable_defaults(theme_fun = theme_apa, split = NULL, 
#                        keep_with_next = NULL, border.width = 0.5)

ftTheme <- function(table){
  table <- table %>% 
    width(width = tblwidth) %>%
    align(i = NULL, j = NULL, align = "right",  part = "all") %>% 
    align(i = 1,    j = NULL, align = "center", part = "header") %>% 
    align(i = NULL, j = 1,    align = "left",   part = "all") %>% 
    fontsize(size = 11, part = "all") %>% 
    border_inner(border = fp_border(color="black", width = 0.5), part = "body")  %>% 
    border_outer(border = fp_border(color="black", width = 0.5), part = "body")  %>% 
    border_inner(border = fp_border(color="black", width = 0.5), part = "header") %>% 
    border_outer(border = fp_border(color="black", width = 0.5), part = "header")
  table
}

```


# Tables {#sec-tables .unnumbered}

```{=latex}
\renewcommand{\baselinestretch}{1}\normalsize
```
```{r}
#| echo: false
#| message: false
#| label: tbl-table1
#| tbl-cap: Characteristics of primary health care and hospitalized patients with skin and soft tissue infections between July 2018 and June 2019 in Northern Division, Fiji.

table1   <- readRDS(file = "../output/table1.rds")
tblwidth <- c(1.75, 1.00, 1.00, 1.00, 1.00)
table1   <- add_footer_lines(table1, value = as_paragraph(c("Percentages may not total 100 due to rounding. IQR, interquartile range; NA, not applicable", " ")))
ftTheme(table1)
```

{{< pagebreak >}}

```{r}
#| echo: false
#| message: false
#| label: tbl-table2
#| tbl-cap: Mean costs per patient (in 2020 Fiji dollars) by resource use category of scabies- and non-scabies-related SSTIs in Northern Division, Fiji.

table2   <- readRDS(file = "../output/table2.rds")
tblwidth <- c(1.75, 1.00, 1.00, 1.00, 1.00)
ftTheme(table2)
```

{{< pagebreak >}}

```{r}
#| echo: false
#| message: false
#| label: tbl-table3
#| tbl-cap: Estimated total annual number of cases, hospitalizations, and costs (in 2020 Fiji dollars) of scabies- and non-scabies-related SSTIs, extrapolated to all four divisions in Fiji based on 2017 census figures.

table3   <- readRDS(file = "../output/table3.rds")
tblwidth <- c(2.75, 1.00, 1.00, 1.00)
ftTheme(table3)
```

{{< pagebreak >}}

# Supplementary Tables {.unnumbered}

```{r}
#| echo: false
#| message: false
#| label: tbl-sTable2
#| tbl-cap: Healthcare resource utilization and costs (in 2020 Fiji dollars) of primary healthcare visits for scabies- and non-scabies-related SSTIs in Northern Division, Fiji.

sTable2   <- readRDS(file = "../output/sTable2.rds")
tblwidth <- c(1.75, 1.00, 1.00, 1.00, 1.00)
ftTheme(sTable2)
```

{{< pagebreak >}}

```{r}
#| echo: false
#| message: false
#| label: tbl-sTable3
#| tbl-cap: Healthcare resource utilization and mean costs (in 2020 Fiji dollars) of hospital admissions with scabies- and non-scabies-related SSTIs in Northern Division, Fiji.

sTable3   <- readRDS(file = "../output/sTable3.rds")
tblwidth <- c(1.75, 1.00, 1.00, 1.00, 1.00)
ftTheme(sTable3)
```

{{< pagebreak >}}

```{r}
#| echo: false
#| message: false
#| label: tbl-sTable4
#| tbl-cap: Total costs (in 2020 Fiji dollars) by patient characteristics of scabies- and non-scabies-related SSTIs in Northern Division, Fiji.

sTable4   <- readRDS(file = "../output/sTable4.rds")
tblwidth <- c(1.75, 1.00, 1.00, 1.00, 1.00)
ftTheme(sTable4)
```
